### ISSUE TITLE
Add armv8 Arch Images

### ISSUE THREAD

**Issue by mytlogos** [GioF71/mpd-pulse-docker#4]
First, thank you for the Image you have created and uploaded.

With the Advent of the Raspberry Pi 4 Series and the new Mac Hardware, it would be great if you could also add the armv8 Architecture for building the images and upload them to DockerHub.

I tested it on a Raspberry Pi 400 and works as it should:
`docker build https://github.com/GioF71/mpd-pulse-docker.git#main -t giof71/mpd-pulse:stable`

**Comment by GioF71** [comment]
Hello, I just manually built the images adding the armv8 version.
The process is not yet automated using GitHub Action so I am leaving the issue open.
Can you verify that the image works properly?

**Comment by mytlogos** [comment]
I tested it on the same Raspberry Pi 400 Device with the following docker-compose file:
```yaml
---
version: "3"
services:
  mpd-pulse:
    image: giof71/mpd-pulse:latest
    ports:
      - 6600:6600
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ./music:/music:ro
      - ./mpd/db:/db
      - ./mpd/playlists:/playlists
```
Software Version:
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
Docker: 20.10.13

Client: mpdevil 1.6.0

Currently the image works properly.
No error logs or problems occurred.
Music plays properly from server.
