### ISSUE TITLE
[doc]: Clarify Configuration of mpd

### ISSUE THREAD

**Issue by mytlogos** [GioF71/mpd-pulse-docker#5]
It is a bit unclear for a "newbie", how mpd can be configured in this image, especially at first glance.

After a bit of searching, i copied the mpd-template.conf, modified that file and mounted it as a "volume", so that at container start the startup script "run-mpd.sh" uses my modified configuration for its templating.
Is that how it was intended?

Example Compose File:
```yaml
---
version: "3"
services:
  mpd-pulse:
    image: giof71/mpd-pulse:stable
    ports:
      - 6600:6600
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ./Music:/music:ro
      - ./mpd/db:/db
      - ./mpd/playlists:/playlists
      - ./mpd-template.conf:/app/assets/mpd-template.conf
```

It would help to document, on how to configure the mpd image. If it is too much of a hassle for you, i could write a PR first.

**Comment by GioF71** [comment]
Hello, the idea behind this repo and others I created for audio (see [squeezelite-docker](https://github.com/GioF71/squeezelite-docker) as the most complete) is that the container should be configured by simply using environment variables, with minimum (or marginal) need for configuration files to be mounted. In the case of mpd of course you should mount your library/playlist/db paths, but it is not required (nor advised) to mount the configuration file.
The configuration you are trying might work but it's not the way it was intended.

This container specifically is geared toward mpd-pulse, so there should be no need to configure mpd.conf, at least not for output configurations. If you want to use alsa, there is the mpd-alsa-docker repository.

On the other hard, this repo is far behind in terms of configurability if you compare it to its "brother" squeezelite-docker.
What are you trying to achieve with your config file? Maybe I can support your request somehow while maintaining the focus on the original objectives.

**Comment by mytlogos** [comment]
My goal was relatively untypical, i wanted to add the http audio output, so that i can play music from mpd as well as any possible clients:

```conf
audio_output {                                                                                                                  
	type            "httpd"
	name          "HTTP Stream"
	port            "8000"
       always_on    "yes"	# prevent MPD from disconnecting all listeners when playback is stopped.
	tags            "yes"	# httpd supports sending tags to listening streams.
}    
```

**Comment by GioF71** [comment]
Ok, so maybe one variable to enable the output (possible name MPD_PULSE_ENABLE_HTTPD) and the other variables, one for each parameter, effective only if the first if set to "Y" might do the trick.
Would that sound good?

**Comment by mytlogos** [comment]
Sounds good.

**Comment by GioF71** [comment]
Hello, can you try and build from this branch:

https://github.com/GioF71/mpd-pulse-docker/tree/feature/optional-httpd-streaming

You might want to build to a different tag so you don't untag your current image, like this for example:

docker build . -t giof71/mpd-pulse:httpd

Then follow these steps:
- Use the tag "httpd" insted of latest or stable in your compose file.
- Expose the port 8080 (like you are already doing with your stack which mounts a different config)
- enable httpd streaming adding the variable "MPD_PULSE_ENABLE_HTTPD=Y"
- Tune the other variables if needed, see the README.md on the same branch

Can you let me know if this works for you?

**Comment by mytlogos** [comment]
It worked with
`docker build https://github.com/GioF71/mpd-pulse-docker.git#feature/optional-httpd-streaming -t giof71/mpd-pulse:httpd`
and

```yaml
---
version: "3"
services:
  mpd-pulse:
    image: giof71/mpd-pulse:httpd
    ports:
      - 6600:6600
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
      - MPD_PULSE_ENABLE_HTTPD=yes
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ./Music:/music:ro
      - ./mpd/db:/db
      - ./mpd/playlists:/playlists

```
Client: M.A.L.P (Android)
